### ISSUE TITLE
Audit / Update README instructions

### ISSUE THREAD

**Issue by jonoliver** [sparkbox/code-challenge-gilded-rose#7]
## Summary

The readme was copied from the [source repo](https://github.com/guyroyse/gilded-rose-javascript). A few changes to the codebase have been made to promote better modularity / testing practices. 

## Tasks

- [ ] Audit existing readme for stale info
- [ ] Add instructions for getting started
  - [ ] Installing dependencies
  - [ ] Running Jest tests
  - [ ] Running Mocha tests
