### ISSUE TITLE
docs: add resources for strategy pattern

### ISSUE THREAD

**Issue by jonoliver** [sparkbox/code-challenge-gilded-rose#8]
## Summary
For our purposes, the intent of this exercise is to help devs gain familiarity with the [Strategy Pattern](https://sourcemaking.com/design_patterns/strategy). This a problem that lends itself well to this pattern, where the rules for each type of item can be encapsulated into a separate strategy that shares the same interface (`Item` → `Item`). An abstraction is then introduced with this same interface, which serves to encapsulate the logic determining which strategy to use for a given `Item` (based on the item's `type` property).

## Caveats
The Strategy pattern is one of the ancient design patterns that was originally prescribed for statically typed languages.  As such, Many of the resources available are focused on introducing abstractions relevant to static types. It might be helpful to explain how to apply the _principals_ of the pattern to our code design, rather than a verbatim implementation.

## Tasks
- [ ] Update the README with:
  - [ ] A description of the pattern and why it's useful
  - [ ] How it relates to this challenge
  - [ ] resource links to the strategy pattern
